version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: volkan-mongodb
  seeder:
    build: ./mongo-seed
    links:
      - mongodb
  api:
    environment: 
      - NODE_ENV=production
      - MONGO_URL=mongodb://volkan-mongodb:27017/volkan-mongodb
      - PORT=8080
    build: ./node
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    container_name: volkan-api
  client:
    build: 
      context: ./react
      args: 
        - REACT_APP_BASE_URL=http://localhost:8080
    ports:
      - "80:80"
    container_name: volkan-client
  